Speed up CI "Initial JDK 11 Build" & fix some dependency gaps
- build in parallel and prevent generate-code failure in quarkus-cli due to missing quarkus-arc-deployment
- fix "dependency gaps" via new update-extension-dependencies.sh support script
- don't execute any maven invoker tests

diff --git a/.github/workflows/ci-actions.yml b/.github/workflows/ci-actions.yml
--- a/.github/workflows/ci-actions.yml
+++ b/.github/workflows/ci-actions.yml
@@ -90,7 +90,16 @@ jobs:
           key: q2maven-${{ steps.get-date.outputs.date }}
       - name: Build
         run: |
-          mvn -e -B -DskipTests -DskipITs -Dno-format clean install
+          mvn -T1C -e -B -DskipTests -DskipITs -Dinvoker.skip -Dno-format clean install
+      - name: Verify extension dependencies
+        shell: bash
+        run: |
+          ./update-extension-dependencies.sh
+          if [ `git status -s -u no '*pom.xml' | wc -l` -ne 0 ]
+          then
+            echo -e '\033[0;31mError:\033[0m Dependencies to extension artifacts are outdated! Run ./update-extension-dependencies.sh and add the modified pom.xml files to your commit.' 1>&2
+            exit 1
+          fi
       - name: Tar Maven Repo
         shell: bash
         run: tar -czf maven-repo.tgz -C ~ .m2/repository
